# Generated by Django 2.1.5 on 2019-06-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fullname', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('Profile_Pic', models.ImageField(upload_to='images/')),
                ('employee_status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Desable')], default='Male', max_length=10)),
            ],
        ),
    ]
